### PR TITLE
Theme

### PR DESCRIPTION
**Pull request by mikespub**
Add composer.json + fix bookPath lookup in main.js to work with templated bookPath urls in `index.html`

```html
	<!-- Reader -->
	<script src="js/epubreader.js"></script>

	<!-- Initialize bookPath -->
	<script>
		window.bookPath = "{{link}}";
	</script>
```

### CODE REVIEW

**Comment by intity** [comment]
I can add `window.bookPath` but no changes to `index.html`. Can you configure webpack in the context of the target application?

**Comment by mikespub** [comment]
Yes, there's no need to update your index.html as I'm using my own template file. This was simply to explain how & why I changed src/main.js to look for window.bookPath :-)

And yes, I'll rebuild the dist/* files before repackaging my fork for PHP composer - I don't know much about javascript development, but executing 1 command is no problem :-)

Unfortunately I'm not sure how to exclude them from a pull request to your upstream repo when I make changes, so feel free to close this PR if you've applied the minor change to main.js

Thanks for all the tweaking for these weird/old devices...

**Comment by intity** [comment]
If the user opens the file on the computer, then priority will be given to storage loading. Defining `window.bookPath` will not change anything when the reader is rebooted. If you need to open a workbook at a given path, you need to override the `window.onload` event. For example,
```html
<!-- Reader -->
<script src="js/epubreader.js"></script>
<script type="text/javascript">
	const path = "https://s3.amazonaws.com/epubjs/books/alice.epub"
	window.onload = (e) => {
		epubreader.main(path, { restore: true, openbook: false });
		e.stopPropagation();
	}
</script>
```
Please note that in this configuration it is necessary to hide the `openbook` button because the `Storage` object is not initialized.

**Comment by mikespub** [comment]
Thanks. I'm not sure I understand the issue you mentioned, as we're talking about a webpage generated by a PHP web application with the bookPath set to an URL depending on which book was selected on the website.

And it does **not** download/link to the full .epub file, only the starting path from which epub.js will download individual file components starting with META-INF/container.xml, then the .opf file etc.

**Comment by intity** [comment]
If the user has a previously opened file stored in the browser from the local computer, then when reloading the reader the book will be loaded from `indexedDB`. This behavior can be changed by explicitly specifying `?bookPath=` in the query string or by overriding the `window.onload` event.

**Comment by mikespub** [comment]
OK, got it - thanks :-)

I changed the template to include the window.onload event as you showed in https://github.com/mikespub-org/intity-epubjs-reader/issues/2 using the exported main()

**Pull request closed without merging**
